import type React from "react"
import type { Metadata } from "next"
import { Space_Grotesk, JetBrains_Mono } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import { ErrorBoundary } from "@/components/error-boundary"
import { getSiteUrl } from "@/lib/env"
import "./globals.css"
import "../styles/animations.css"

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
  preload: true,
})

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
  preload: true,
})

const siteUrl = getSiteUrl()

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "CloudSaver - Find Hidden Savings in Your DigitalOcean Infrastructure",
    template: "%s | CloudSaver",
  },
  description:
    "Paste your DigitalOcean token. Get a free report in under 30 seconds showing where you can cut costs. Read-only access, no sign-up. 11 checks across droplets, volumes, snapshots, and more.",
  keywords: [
    "DigitalOcean",
    "cloud cost optimization",
    "infrastructure analysis",
    "cost savings",
    "cloud infrastructure",
    "droplet optimization",
    "zombie resources",
    "cloud waste",
    "infrastructure audit",
  ],
  authors: [{ name: "Angel Cruz", url: "https://www.angelcruz.dev" }],
  creator: "Angel Cruz",
  publisher: "CloudSaver",
  applicationName: "CloudSaver",
  category: "Developer Tools",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "CloudSaver",
    title: "CloudSaver - Find Hidden Savings in Your DigitalOcean Infrastructure",
    description:
      "Free report in under 30 seconds. See where you're overpaying on DigitalOcean—droplets, volumes, snapshots, and more. Read-only, no sign-up.",
    // Images auto-generated by app/opengraph-image.tsx
    determiner: "auto",
    countryName: "United States",
  },
  twitter: {
    card: "summary_large_image",
    title: "CloudSaver - Find Hidden Savings in Your DigitalOcean Infrastructure",
    description:
      "Free report in under 30 seconds. See where you're overpaying on DigitalOcean—droplets, volumes, snapshots, and more. Read-only, no sign-up.",
    // Image auto-generated by app/twitter-image.tsx
    creator: "@abr4xas",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      {
        url: "/icon-light-32x32.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icon-dark-32x32.png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
    apple: "/apple-icon.png",
  },
  verification: {
    // Add Google Search Console verification if needed
    // google: process.env.GOOGLE_SITE_VERIFICATION,
    // Add other verification services
    // yandex: process.env.YANDEX_VERIFICATION,
    // bing: process.env.BING_VERIFICATION,
  },
  // Additional metadata
  other: {
    "theme-color": "#18181b", // Dark theme color for mobile browsers
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark" style={{ scrollBehavior: "smooth" }}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={`${spaceGrotesk.variable} ${jetbrainsMono.variable} font-sans antialiased`}>
        <ErrorBoundary>
          {children}
        </ErrorBoundary>
        <Analytics />
      </body>
    </html>
  )
}
